---
- hosts: masters
  become: yes
  tasks:

    - name: initialize the cluster
      shell: kubeadm init --apiserver-advertise-address=192.168.99.10 --pod-network-cidr=192.168.0.0/16  --ignore-preflight-errors=all
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      
    - name: create kube directory
      file:
        path: $HOME/kube
        state: directory
        mode: 0755
        owner: kube 
        group: kube 

    - name: create .kube directory
      file:
        path: /home/kube/.kube
        state: directory
        mode: 0755
        owner: kube 
        group: kube 

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
      args:
        chdir: /home/kube
        
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: kube
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
       msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

