---
- name: "Install, configure, and start k8s master node"
  block:
    - name: "k8s:: Pull images"
      shell: kubeadm config images pull
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: "Initialize the cluster"
      shell: kubeadm init --apiserver-advertise-address="{{ k8s_apiserver_advertise_address }}" --pod-network-cidr="{{ k8s_pod_network_cidr }}" --ignore-preflight-errors=all
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      
    - name: create kube directory
      file:
        path: $HOME/kube
        state: directory
        mode: 0755
        owner: kube 
        group: kube 

    - name: create .kube directory
      file:
        path: /home/kube/.kube
        state: directory
        mode: 0755
        owner: kube 
        group: kube 

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f "{{ k8s_network_calico }}"
      args:
        chdir: /home/kube
        
    - name: "Get the token for joining the worker nodes"
      become: yes
      become_user: kube
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command
      ignore_errors: "{{ ansible_check_mode }}" 

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
      ignore_errors: "{{ ansible_check_mode }}" 
