---
- name: Copy join command from Ansiblehost to the worker nodes.
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777
  ignore_errors: "{{ ansible_check_mode }}" 
  

- name: "Join the Worker nodes to the cluster."
  shell:
    cmd: sh /tmp/kubernetes_join_command
  ignore_errors: "{{ ansible_check_mode }}" 

